# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a983953428f3ed21993843d510a425830e3f222b27c5da63a9218731afbf61b1c185da076de58132fd5f9c648412579f0c8ab35a6b65929e1a74a5a30deb23f4

test:
  secret_key_base: 7edce7f0c9ded89ed89e536951c8ec36f97d7ec907b8a5d6a39f09875fb36a3780df7ba49390a3aeb75e3974b88974d01298daafb7d1bc0f798e0b92d2302bbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
